WITH TOTAL_INFO AS (
    select JULY.FLAVOR, SUM(JULY.TOTAL_ORDER + FH.TOTAL_ORDER) TOTAL
    from FIRST_HALF FH join JULY on FH.FLAVOR = JULY.FLAVOR
    GROUP BY JULY.FLAVOR
    ORDER BY TOTAL DESC
)

SELECT FLAVOR
FROM TOTAL_INFO
LIMIT 3;
