WITH TIME_TABLE AS (
    SELECT (ROW_NUMBER() OVER () - 1) AS H
    FROM INFORMATION_SCHEMA.TABLES
    LIMIT 24
)

SELECT TT.H, COUNT(HOUR(AO.DATETIME)) COUNT
FROM ANIMAL_OUTS AO RIGHT OUTER JOIN TIME_TABLE TT ON HOUR(AO.DATETIME) = TT.H
GROUP BY TT.H;