WITH RECURSIVE TT AS(
    SELECT 0 H
    UNION ALL
    SELECT H+1
    FROM TT
    WHERE H < 23
)

SELECT TT.H, COUNT(HOUR(AO.DATETIME)) COUNT
FROM ANIMAL_OUTS AO RIGHT OUTER JOIN TT ON HOUR(AO.DATETIME) = TT.H
GROUP BY TT.H;